#!/usr/bin/env python3
"""Put the project's real changelog into the status section.

The status section used to be a hand-written list, which is a claim that goes
stale silently. It now renders `CHANGELOG.md` from `dedalo-org/dedalo` — the
same file `git-cliff` writes at release time — so the page says what the
project says, or it fails.

**Truncated on purpose.** A changelog grows without limit and a landing page
does not: at most three sections, at most six entries each, and a link to the
whole thing. What is dropped is dropped visibly, with a count, because a list
that quietly stops being complete is worse than a shorter one that says so.

**Not fetched by the page.** The site's Content-Security-Policy is
`default-src 'none'` and that is worth more than freshness measured in seconds.
This runs at build time and the workflow reruns on a schedule, so "dynamic"
here means the deploy is current rather than the browser is.

The committed page keeps the last generated copy rather than a placeholder, so
opening `site/index.html` locally shows something true — just possibly a few
days old.

    scripts/sync-changelog.py            # print what would be written
    scripts/sync-changelog.py --write    # update site/index.html
    scripts/sync-changelog.py --source PATH   # read a local file instead
"""

from __future__ import annotations

import argparse
import html
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "site" / "index.html"

SOURCE = "https://raw.githubusercontent.com/dedalo-org/dedalo/main/CHANGELOG.md"
LINK = "https://github.com/dedalo-org/dedalo/blob/main/CHANGELOG.md"

MAX_SECTIONS = 3
MAX_ENTRIES = 6

START = "<!-- changelog:start -->"
END = "<!-- changelog:end -->"


def fetch(source: str | None) -> str:
    """The changelog, from a local path or from the repository."""
    if source:
        return Path(source).read_text()
    request = urllib.request.Request(
        SOURCE, headers={"User-Agent": "dedalo-org.github.io (build)"}
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode()


def sections(changelog: str) -> list[tuple[str, str, list[str]]]:
    """Every `## version — date` section, newest first.

    Returns `(heading, date, entries)`. Entries are the bullet points across
    every `###` subsection, flattened: a landing page has no room to reproduce
    "Added" and "Known limitations" as separate lists, and the distinction is
    one click away in the real file.
    """
    found = []
    for block in re.split(r"^## ", changelog, flags=re.M)[1:]:
        lines = block.splitlines()
        heading = lines[0].strip()
        title, _, date = heading.partition("—")
        entries = []
        current = ""
        for line in lines[1:]:
            if line.startswith("## "):
                break
            if line.startswith("- "):
                if current:
                    entries.append(current)
                current = line[2:].strip()
            elif current and line.startswith("  "):
                current += " " + line.strip()
            elif current and not line.strip():
                entries.append(current)
                current = ""
        if current:
            entries.append(current)
        found.append((title.strip(), date.strip(), entries))
    return found


INLINE_CODE = re.compile(r"`([^`]+)`")
BOLD = re.compile(r"\*\*([^*]+)\*\*")
LINK_MD = re.compile(r"\[([^\]]+)\]\([^)]+\)")


def render_entry(text: str) -> str:
    """One bullet, as safe HTML.

    Escaped first and marked up second, so a changelog is content rather than
    a template — nothing in that file should be able to add an element to this
    page.
    """
    safe = html.escape(text)
    safe = LINK_MD.sub(r"\1", safe)
    safe = INLINE_CODE.sub(r"<code>\1</code>", safe)
    safe = BOLD.sub(r"<b>\1</b>", safe)
    return safe


def render(found: list[tuple[str, str, list[str]]]) -> str:
    """The whole block, ready to sit between the markers."""
    out = [
        "",
        "    <!-- Generated by scripts/sync-changelog.py from the changelog in",
        "         dedalo-org/dedalo. Do not edit between the markers: the next",
        "         build will overwrite it. -->",
        '    <ol class="changelog">',
    ]
    for title, date, entries in found[:MAX_SECTIONS]:
        shown = entries[:MAX_ENTRIES]
        dropped = len(entries) - len(shown)
        out.append("      <li>")
        out.append(
            f'        <h3><span class="cl-version">{html.escape(title)}</span>'
            + (f'<span class="cl-date">{html.escape(date)}</span>' if date else
               '<span class="cl-date">not released</span>')
            + "</h3>"
        )
        out.append("        <ul>")
        for entry in shown:
            out.append(f"          <li>{render_entry(entry)}</li>")
        if dropped:
            out.append(
                f'          <li class="cl-more">and {dropped} more in the '
                "changelog</li>"
            )
        out.append("        </ul>")
        out.append("      </li>")
    out.append("    </ol>")
    total = len(found)
    if total > MAX_SECTIONS:
        out.append(
            f'    <p class="sub">Showing {MAX_SECTIONS} of {total} releases. '
            f'<a href="{LINK}">The full changelog</a> is in the repository.</p>'
        )
    else:
        out.append(
            f'    <p class="sub"><a href="{LINK}">The full changelog</a> '
            "is in the repository, and this is generated from it.</p>"
        )
    out.append("    ")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="update site/index.html")
    parser.add_argument("--source", help="read a local changelog instead of fetching")
    args = parser.parse_args()

    try:
        changelog = fetch(args.source)
    except (urllib.error.URLError, OSError) as error:
        # Loudly. A page that silently shows nothing where the changelog goes
        # is worse than a build that stops: the previous deploy stays up, and
        # it was at least true when it was made.
        print(f"error: cannot read the changelog: {error}", file=sys.stderr)
        return 1

    found = sections(changelog)
    if not found:
        print("error: no `## version` sections in the changelog", file=sys.stderr)
        return 1

    block = render(found)
    if not args.write:
        print(block)
        return 0

    page = PAGE.read_text()
    if START not in page or END not in page:
        print(f"error: {START} / {END} markers not found in {PAGE}", file=sys.stderr)
        return 1

    before, _, rest = page.partition(START)
    _, _, after = rest.partition(END)
    PAGE.write_text(before + START + block + END + after)

    shown = sum(min(len(e), MAX_ENTRIES) for _, _, e in found[:MAX_SECTIONS])
    print(
        f"wrote {min(len(found), MAX_SECTIONS)} of {len(found)} sections "
        f"({shown} entries) into {PAGE.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
